name: Deploy on Push

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/dev'
        run: |
          # Replace with your deployment script or command
          echo "Deploying to Staging"
          cd /home/ec2-user/workspace/deploy-with-github-actions/_work/dev
          npm ci

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          # Replace with your deployment script or command
          echo "Deploying to Production"
          cd /home/ec2-user/workspace/deploy-with-github-actions/_work/prod
          npm ci
